config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'session/new'

  get 'user/new'

  get 'page_home/home'

  get 'page_home/help'

  get 'page_home/about'

  get 'page_home/contact'

  get 'page_home/signup'

  root 'page_home#home'
  get 'home',to:'page_home#home'
  get 'help',to:'page_home#help'
  get 'contact',to:'page_home#contact'
  get 'about',to:'page_home#about'
  get 'signup',to:'users#new'
  get 'login',to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout',to:'sessions#destroy'
  get 'User', to:'page_home#users'
  get 'Post', to:'page_home#microposts'

  resources :users do
    member do
      get   :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
 
  resources :microposts do
    resources :comments
    end      
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many   :comments
  default_scope -> { order(created_at: :desc)}
  mount_uploader :picture, PictureUploader
  validates  :user_id,presence:true
  validates  :content,presence:true, length: { maximum: 150}
  validate  :picture_size

  private

  def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :find_post,       only: [:show, :edit, :update, :destroy]
	before_action :logged_in_user, only:  [:create, :destroy,:edit,:update]
  before_action :correct_user,   only: :destroy

  #Hien thi tat ca cac record trong Model Micropost
  def index
    @feed_items = Micropost.all.paginate(page: params[:page])
  end
  #Hien thi tat ca cac record lien ket
  def show
    @comments = Comment.where(micropost_id: @micropost).order("created_at DESC")
  end

  #Goi ham POST
   def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'page_home/home'
    end
  end

	def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
  end
    def edit
    @micropost = Micropost.find(params[:id])
  end
  def update
    @micropost = Micropost.find(params[:id])
    if @micropost.update_attributes(micropost_params)
      flash[:success] = "Micropost update success!"
      redirect_to request.referrer || root_url
    else
      flash.now[:danger] = "Micropost updated failed!"
      redirect_to request.referrer || root_url
  end
end

  private

  def micropost_params
    params.require(:micropost).permit(:title, :content, :picture)
  end

  def find_post
    @micropost = Micropost.find(params[:id])
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user">
  <% if logged_in? %>
  <%= link_to micropost.user.name, micropost.user %> 
  <% else %>
  <%= link_to micropost.user.name, login_path %> 
  <% end %>
  đã đăng một 
  <%= link_to "bài viết", micropost %>
  </span><br>
   <span class="title"><%= micropost.created_at %></span><br>
   <span class="title"><%= micropost.title %></span><br>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Đã đăng <%= time_ago_in_words(micropost.created_at) %> trước.
    <% if current_user?(micropost.user) %>
      <%= link_to "Xóa bài đăng", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
      <%= link_to "Edit bài đăng", edit_micropost_path(micropost) %>                                 
    <% end %>
   
  </span>
</li>

app/views/microposts/edit.html.erb
<div class="col-sm-2"></div>
<div class="col-sm-8">
<div class="content-status">
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  <%= f.submit "Đăng", class: "btn btn-primary button-post" %>
<% end %>

<script type="text/javascript">
	  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>
</div>

app/views/microposts/index.html.erb
<div class="col-md-2"></div>
<% if @feed_items.any? %>
<div class="col-md-6">
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
 </div>
  <%= will_paginate @feed_items %>
<% end %>

app/views/microposts/show.html.erb
<div class="col-sm-2"></div>
<div class="col-sm-8">
<div class="content-status">
<p class="avatar-user"><%= link_to gravatar_for(@micropost.user, size: 50), @micropost.user %><%= link_to @micropost.user.name ,@micropost.user%> <%= time_ago_in_words(@micropost.created_at) %> trước. </p>
<p><%= @micropost.content %></p>
 <%= image_tag @micropost.picture.url if @micropost.picture? %>
</div>
<% if logged_in? %>
<%= form_for([@micropost, @micropost.comments.build]) do |f| %>
 <%= f.text_area :content %>
 <div class="sub-comment"><%= f.submit "Comment", class: 'btn btn-success subm-comment pull-right' %></div>
 <% end %>
  <strong id="followers" class="stat">
      <%= @comments.count %> comments
  </strong>
 <% @comments.each do |followers| %>
<p><%= link_to gravatar_for(f.user, size: 20) %><strong class="username-comment"><%= f.user.name %></strong>  <%= f.content %>  
<% if current_user?(f.user) %>   
  <i class="glyphicon glyphicon-trash i-delete"><%= link_to "Xóa",[f.micropost, f], method: :delete %></i></p>
	<% end %>
<% end %>
 <% else %>
<%= form_for([@micropost, @micropost.comments.build]) do |f| %>
 <%= f.text_area :content %>
<%= link_to "Comment" ,login_path%>
 <% end %>
 <strong id="followers" class="stat">
      <%= @comments.count %> comments
  </strong>
 <% @comments.each do |f| %>
<p><%= link_to gravatar_for(f.user, size: 20) %><strong class="username-comment"><%= f.user.name %></strong>  <%= f.content %>     
<% if logged_in? %>   
<%= link_to "Xóa",[f.micropost, f], method: :delete %></p>
	<% end %></p>
	
<% end %>
</div>		
 <% end %>
</div>