config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'session/new'

  get 'user/new'

  get 'page_home/home'

  get 'page_home/help'

  get 'page_home/about'

  get 'page_home/contact'

  get 'page_home/signup'

  root 'page_home#home'
  get 'home',to:'page_home#home'
  get 'help',to:'page_home#help'
  get 'contact',to:'page_home#contact'
  get 'about',to:'page_home#about'
  get 'signup',to:'users#new'
  get 'login',to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout',to:'sessions#destroy'
  get 'User', to:'page_home#users'
  get 'Post', to:'page_home#microposts'

  resources :users do
    member do
      get   :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
 
  resources :microposts do
    resources :comments
    end      
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/page_home_controller.rb
class PageHomeController < ApplicationController
  def home
     if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = Micropost.all.paginate(page: params[:page])
      #@users = User.paginate(page: params[:page])
      # @comments = Comment.where(micropost_id: @micropost).order("created_at DESC")
        if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order("created_at DESC")
    end
    end
  end

  def help
  end

  def about
  	
  end
  def contact
  	
  end
  def signup
    
  end
  
end

app/helpers/page_home_helper.rb
module PageHomeHelper
end

app/views/page_home/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/page_home/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/page_home/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/page_home/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-3">
    </aside>
    <div class="col-md-8">
      <section class="micropost_form">
         <%= render 'shared/micropost_form' %>
      </section>
      <%= render 'shared/feed' %>
    </div>
    <!-- <div class="col-md-2"></div> -->
  </div>
<% else %>
<div class="col-sm-6">
  <div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>

    <h2 class="image-home-page">
    <%= link_to image_tag("social-connect.png", alt: "Rails logo"),
              'http://rubyonrails.org/' %>
    </h2>
  </div>
</div>
<div class="col-sm-6">
  <h1>Sample App</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span>Remember me on this computer</span>
      <% end %>
      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
    <br>
    <div class="forget_pass">
       <%= link_to "Forget Password", new_password_reset_path %>
         </div>
    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>

<% end %>
</div>