config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'session/new'

  get 'user/new'

  get 'page_home/home'

  get 'page_home/help'

  get 'page_home/about'

  get 'page_home/contact'

  get 'page_home/signup'

  root 'page_home#home'
  get 'home',to:'page_home#home'
  get 'help',to:'page_home#help'
  get 'contact',to:'page_home#contact'
  get 'about',to:'page_home#about'
  get 'signup',to:'users#new'
  get 'login',to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout',to:'sessions#destroy'
  get 'User', to:'page_home#users'
  get 'Post', to:'page_home#microposts'

  resources :users do
    member do
      get   :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
 
  resources :microposts do
    resources :comments
    end      
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer footer-content">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", contact_path %></li>

      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-head-top">
  <div class="container">
    <%= link_to "sample app",microposts_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right nav-head-top">
        <% if logged_in? %>
        <li><%= link_to @current_user.name,   current_user %></li>
        <li><%= link_to "Trang chu",   home_path %></li>
        <li><%= link_to "User",   users_path %></li>
        <li><%= link_to "Post",   microposts_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
 
              <b class="caret"></b></a>
            <ul class="dropdown-menu item-settings">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Setting", edit_user_path(current_user) %></li>
              <li class="divider">
              </li>
              <li>
                  <%= link_to "Log out",logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container content-infor">
     <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
        <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
     <%= render 'layouts/footer' %>
  </body>
</html>